name: objectboxexample
description: An example objectbox.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.7.0
  objectbox_flutter_libs: any


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any


flutter:


  uses-material-design: true


